version: '3.8'

services:
  research-paper-evaluator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: research-paper-evaluator
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped

networks:
  default:
    name: research-paper-evaluator-network

volumes:
  data:
    driver: local